run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck

linters-settings:
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 15
  gocyclo:
    min-complexity: 15
  cyclop:
    max-complexity: 15
  lll:
    line-length: 120
  varnamelen:
    min-name-length: 2
    ignore-names:
      - err
      - id
      - ok
      - r
      - w
      - t
      - i
      - j
      - k
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
  goheader:
    template-path: .go-header.txt
  revive:
    rules:
      - name: exported
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocognit
        - gocyclo
        - cyclop
        - dupl
        - varnamelen
        - gomnd
    - path: examples/
      linters:
        - forbidigo
        - gomnd
        - varnamelen
    - linters:
        - lll
      source: "^//go:generate "