run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - err113
    - gofmt
    - gofumpt
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - usetesting
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck

linters-settings:
  funlen:
    lines: 120
    statements: 60
  gocognit:
    min-complexity: 25
  gocyclo:
    min-complexity: 25
  cyclop:
    max-complexity: 25
  lll:
    line-length: 120
  varnamelen:
    min-name-length: 2
    ignore-names:
      - err
      - id
      - ok
      - r
      - w
      - t
      - i
      - j
      - k
      - fn
      - ch
      - db
      - fs
      - wg
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
  nestif:
    min-complexity: 6
  dupl:
    threshold: 150
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
  err113:
    max-wrapped-stack-depth: 3
  revive:
    rules:
      - name: exported
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocognit
        - gocyclo
        - cyclop
        - dupl
        - varnamelen
        - mnd
        - tagliatelle
        - testpackage
        - thelper
        - noctx
        - gofumpt
    - path: examples/
      linters:
        - forbidigo
        - mnd
        - varnamelen
    - linters:
        - lll
      source: "^//go:generate "