components: {}
info:
    description: A simple API for managing users with automatic OpenAPI generation
    title: User Management API
    version: 1.0.0
openapi: 3.0.3
paths:
    /users:
        post:
            requestBody:
                content:
                    multipart/form-data:
                        schema:
                            properties:
                                avatar:
                                    format: binary
                                    type: string
                            type: object
            responses:
                "201":
                    content:
                        application/json:
                            schema:
                                properties:
                                    created_at:
                                        type: string
                                    email:
                                        type: string
                                    id:
                                        type: string
                                    name:
                                        type: string
                                required:
                                    - id
                                    - name
                                    - email
                                    - created_at
                                type: object
                    description: Created
    /users/{id}:
        get:
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                    format: uuid
                    type: string
                - in: query
                  name: fields
                  schema:
                    default: id,name,email
                    type: string
                - in: header
                  name: Authorization
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    email:
                                        type: string
                                    id:
                                        type: string
                                    name:
                                        type: string
                                required:
                                    - id
                                    - name
                                type: object
                    description: Success
servers:
    - description: Development server
      url: http://localhost:8080
